### ISSUE TITLE
OleDB Alternative

### ISSUE THREAD

**Issue by allejo** [allejo/SODA.NET#1]
Possibly worth looking into: https://github.com/ExcelDataReader/ExcelDataReader

**Comment by thekaveman** [comment]
This definitely looks interesting! I like that they make a Nuget package available - we would be able to take that as a dependency in the SODA.NET package.

**Comment by allejo** [comment]
Tested the package in the [feature-exceldatareader](https://github.com/allejo/SODA.NET/tree/feature-exceldatareader) branch.
